server:
  port: 8080

app:
  openai:
    api-key: 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
    base-url: https://api.openai.com/v1
    # Recommend configuring the model to one that matches your token/cost needs.
    embedding-model: text-embedding-3-small
    chat-model: gpt-4o-mini   # change to a model you have access to (or 8k model)
